/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controller.ClienteController;
import Funcoes.Funcoes;
import Models.Cliente;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Taffarel
 */
public class TelaLogin extends javax.swing.JDialog {

    /**
     *
     */
    private static int QUANTIDADE_ERRO_LOGIN_PERMITIDO = 2;

    /**
     * Creates new form NewJDialog
     */
    public TelaLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        String[] r = ClienteController.getUltimoLogin();

        DecimalFormat decimalFormat = new DecimalFormat("#####");
        NumberFormatter textFormatter = new NumberFormatter(decimalFormat);
        textFormatter.setMaximum(99999);
        textFormatter.setOverwriteMode(true);
        textFormatter.setAllowsInvalid(false);
        jFormattedTextField1.setFormatterFactory(new DefaultFormatterFactory(textFormatter));
        jFormattedTextField1.setText(r[1]);

        //=======================
        DecimalFormat decimalFormat2 = new DecimalFormat("#####");
        NumberFormatter textFormatter2 = new NumberFormatter(decimalFormat2);
        textFormatter2.setMaximum(999999999);
        textFormatter2.setOverwriteMode(true);
        textFormatter2.setAllowsInvalid(false);
        jFormattedTextField2.setFormatterFactory(new DefaultFormatterFactory(textFormatter2));
        jFormattedTextField2.setText(r[0]);

        if (!(jFormattedTextField2.getText().equals("") && jFormattedTextField1.getText().equals(""))) {
            jPasswordField1.requestFocus();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Autenticação");
        setModal(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Autoatendimento Pessoa Física  ");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Users-Exit-icon.png"))); // NOI18N
        jButton3.setText("SAIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Agência:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Conta:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Actions-media-skip-forward-icon.png"))); // NOI18N
        jButton1.setText("AVANÇAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField1FocusGained(evt);
            }
        });
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyReleased(evt);
            }
        });

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFormattedTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField2KeyReleased(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Senha:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(84, 84, 84))
                                .addComponent(jFormattedTextField2))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int reply = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Atenção",
                JOptionPane.YES_NO_OPTION);

        if (reply == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    public void fazerLogin() {

        ClienteController c = new ClienteController();

        if (c.fazerLogin(jFormattedTextField1, jFormattedTextField2)) {

            ResultSet rs = ClienteController.isBloqueado(jFormattedTextField1, jFormattedTextField2);

            try {
                if (rs.next()) {

                    /*0=Bloqueado, 1=Desbloqueado*/
                    int status = rs.getInt("cli_status");
                    /*
                    Um número inteiro. -1=desbloqueado; 
                    0=é o valor inicial quando é adicionado ao sistema;
                    1=bloqueado porque excedeu o limite permitido por*/
                    int bloqueioMotivo = rs.getInt("cli_bloqueio_motivo");
                    
                    //Verifica o motivo de o ClienteController ter sido bloqueado.
                    String mensagemBloqueio = "";
                    //Título da Mensagem
                    String titulo = "";

                    int msgType = 0;

                    //O ClienteController está bloqueado
                    if (status == 0) {

                        switch (bloqueioMotivo) {
                            case -1:
                                titulo = "Seja-bem vindo(a).";
                                msgType = JOptionPane.INFORMATION_MESSAGE;
                                break;
                            case 0:
                                titulo = "Seja-bem vindo(a).";
                                mensagemBloqueio = "Obrigado por escolher o nosso banco.\nPara o primeiro acesso, vá a alguma agência\nmais próxima com seu "
                                        + "cartão e CPF para poder\ndesbloquear o acesso.";
                                msgType = JOptionPane.INFORMATION_MESSAGE;
                                break;
                            case 1:
                                mensagemBloqueio = "Sua conta foi bloqueada por exceder o limite de login em outra sessão."
                                        + "\nPara acessar novamente, vá a alguma de nossas agências para \nque seu acesso seja desbloqueado.";
                                titulo = "Usuário Bloqueado.";
                                msgType = JOptionPane.ERROR_MESSAGE;
                                break;
                            case 2:
                                mensagemBloqueio = "Sua conta está inativa."
                                        + "\nPara acessar ativá-la, vá a alguma de nossas agências para \nque ela volte a ser a tiva.";
                                titulo = "Usuário Inativo.";
                                msgType = JOptionPane.ERROR_MESSAGE;
                                break;
                            default:
                                throw new AssertionError();
                        }

                        JOptionPane.showMessageDialog(null, mensagemBloqueio, titulo, msgType);

                        System.exit(0);
                    } else if (status == 1) {//1=O ClienteController está desbloquado

                        switch (bloqueioMotivo) {
                            case -2:
                                /*Conta Inativa 2=Conta Ativa*/
                                mensagemBloqueio = "Sua conta está inativa."
                                        + "\nPara acessar ativá-la, vá a alguma de nossas agências para \nque ela volte a ser a tiva.";
                                titulo = "Usuário Inativo.";
                                msgType = JOptionPane.ERROR_MESSAGE;
                                JOptionPane.showMessageDialog(null, mensagemBloqueio, titulo, msgType);
                                break;
                            default:
                                Cliente.setNumeroConta(Integer.parseInt(jFormattedTextField2.getText()));

                                c.getDadosCliente(Integer.parseInt(jFormattedTextField1.getText()), Integer.parseInt(jFormattedTextField2.getText()));

                                fazerLoginSegundaParte();
                                break;
                        }

                    }
                } else {

                }
            } catch (SQLException ex) {
                //Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    public void fazerLoginSegundaParte() {
        try {
            ClienteController c = new ClienteController();
            //Número da conta do ClienteController:
            int numeroConta = Integer.parseInt(jFormattedTextField2.getText().trim());

            int numeroAgencia = Integer.parseInt(jFormattedTextField1.getText().trim());

            if (QUANTIDADE_ERRO_LOGIN_PERMITIDO >= -1) {
                //SE for ok
                if (c.verificarSenha(numeroConta, jPasswordField1.getText()) > 0) {
                    //Limpa o campo de senha.
                    jPasswordField1.setText("");

                    //Pega o ID do ClienteControllerController. Verificar a documentação do metódo. Ctrl+Click no método.
                    ClienteController.gravarLogin(numeroConta);

                    Funcoes.setId(numeroConta);

                    ClienteController ClienteController = new ClienteController();

                    ClienteController.getDadosCliente(numeroAgencia, numeroConta);

                    new TelaInicial().setVisible(true);

                    TelaSistema.getFrame().setVisible(false);

                    QUANTIDADE_ERRO_LOGIN_PERMITIDO = 2;

                } else {

                    if (QUANTIDADE_ERRO_LOGIN_PERMITIDO > 0) {
                        JOptionPane.showMessageDialog(null, "Senha incorreta. Você só tem mais "
                                + QUANTIDADE_ERRO_LOGIN_PERMITIDO + " chances.", "Atenção", JOptionPane.ERROR_MESSAGE);
                        jPasswordField1.requestFocus();
                    } else if (QUANTIDADE_ERRO_LOGIN_PERMITIDO == 0) {
                        JOptionPane.showMessageDialog(null, "Última change, e sua conta será bloqueada.",
                                "Atenção", JOptionPane.ERROR_MESSAGE);
                    } else if (QUANTIDADE_ERRO_LOGIN_PERMITIDO == -1) {
                        JOptionPane.showMessageDialog(null, "Você atingiu o máximo limite permitido pelo \n"
                                + "sistema de tentativas de Login. Sua conta foi bloqueada.\n"
                                + "Procure alguma agência mais próxima para poder desbloqueá-la.",
                                "Atenção", JOptionPane.ERROR_MESSAGE);
                        ClienteController.bloquearDesbloquearCliente(0, 1, numeroConta);
                        System.exit(0);
                    }

                    --QUANTIDADE_ERRO_LOGIN_PERMITIDO;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Você atingiu o máximo limite permitido pelo \n"
                        + "sistema de tentativas de Login. Sua conta foi bloqueada.", "Atenção", JOptionPane.ERROR_MESSAGE);
                ClienteController.bloquearDesbloquearCliente(0, 1, numeroConta);
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Atenção", 1);
        }

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fazerLogin();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFormattedTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField1FocusGained
        // TODO add your handling code here:
        jFormattedTextField1.selectAll();
    }//GEN-LAST:event_jFormattedTextField1FocusGained

    private void jFormattedTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            jFormattedTextField2.selectAll();
            jFormattedTextField2.requestFocus();
        }
    }//GEN-LAST:event_jFormattedTextField1KeyReleased

    private void jFormattedTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField2KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            fazerLogin();
        }
    }//GEN-LAST:event_jFormattedTextField2KeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            fazerLoginSegundaParte();
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:

        if (!(jFormattedTextField2.getText().equals("") && jFormattedTextField1.getText().equals(""))) {
            jPasswordField1.requestFocus();
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            TelaLogin dialog = new TelaLogin(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
